### ISSUE TITLE
TypeScript Types

### ISSUE THREAD

**Issue by djskinner** [marudor/libxmljs2#1]
We are looking to move over to libxmljs2 due to being unable to unit test libxmljs due to the issue described in https://github.com/libxmljs/libxmljs/pull/462. It seems very unlikely at this stage that the maintainers are going to accept that PR.

However, we're using TypeScript so it requires an additional step of either creating @types/libxmljs2 (a clone of @types/libxmljs) or adding the typings directly to this library.

I would be happy to contribute typings directly, if it would be accepted. Alternatively I can make the equivalent contribution to DefinitelyTyped. Do the maintainers of this fork have a preferred approach?

**Comment by marudor** [comment]
I would accept them here as well. 
Do what you think is best.

**Comment by marudor** [comment]
I've included the @types/libxmljs types for now. (v0.21.3)
