### ISSUE TITLE
adding support for arm64e (M1 chip)

### ISSUE THREAD

**Issue by Raffaello** [marudor/libxmljs2#186]
Would it be possible to have a arm64 compilation of the library to allow to be used on a M1 chip?

**Comment by marudor** [comment]
I do not have a m1 and github doesn't support that. It should still work though, you will need to build it yourself though.
Should happen automatically on install.

**Comment by Raffaello** [comment]
yes that's right. everything is fine in this pacakge.
Ok i see, if neither GitHub support it. IT would just have been nice to download the release package instead of building it. but ok.

----


I found the issue instead is because of another library using this one: `libxml2js-xsd`
https://github.com/cdegalitt/libxmljs2-xsd/issues/17
