### ISSUE TITLE
Node 12?

### ISSUE THREAD

**Issue by tsabbay** [marudor/libxmljs2#2]
Hi,
Do you have any plans of support Node12 ?

**Comment by marudor** [comment]
Yes - last time I checked node-gyp still has problems. Will update once fixed.

**Comment by tsabbay** [comment]
tx

**Comment by marudor** [comment]
Okay - just deprecations missing.
0.21.0 supports node 12. (Some binaries are still building)

**Comment by lorenzleutgeb** [comment]
Could you please file a PR against libxmljs/libxmljs to upstream compatibility?

**Comment by marudor** [comment]
libxmljs is not maintained. Year old issues are still open there. (I fixed some of those as well)
Please use libxmljs2.
