### ISSUE TITLE
Security vulnerability: "libxmljs2 type confusion vulnerability when parsing specially crafted XML"

### ISSUE THREAD

**Issue by Bekaxp** [marudor/libxmljs2#210]
We are getting an Audit report with the following security vulnerability regarding your package:
https://github.com/advisories/GHSA-mjr4-7xg5-pfvh

Are you already looking into this?

Thank you very much for you support and the library!

**Comment by marudor** [comment]
Hoenstly, I'm not good enough with c++ The only reason I made this is to use it in my own Project (https://github.com/marudor/bahn.expert)
My own project is not vulnerable.
So unless someone else fies it I will most likely not fix this.

**Comment by Bekaxp** [comment]
Thank you for the quick reply. Your library is being used by some packages from https://github.com/CycloneDX. They will for sure get a lot of messages in this regard, so maybe they will help you out fixing it :)

**Comment by fennibay** [comment]
Hi @marudor, thanks for creating and maintaining this project ❤️

I think it would be clearer to keep the issue open until the audit issue resolved, so someone can create a PR to address this.

Regarding a fix, how can I help? Is the issue caused by the underlying [libxml2](https://gitlab.gnome.org/GNOME/libxml2) library? Are its maintainers aware of the issue?

**Comment by fennibay** [comment]
Is this a duplicate of #204?

**Comment by marudor** [comment]
handled in #204

**Comment by jkowalleck** [comment]
> Thank you for the quick reply. Your library is being used by some packages from https://github.com/CycloneDX. They will for sure get a lot of messages in this regard, so maybe they will help you out fixing it :)

Hi, I am the core developer and maintainer of CycloneDX for JavaScript.
I was pinged here https://github.com/CycloneDX/cyclonedx-javascript-library/issues/1061

> They will for sure get a lot of messages in this regard,
Well, I am not aware of any messages in this regard.

Best,
Jan. CC @CycloneDX/core-team
