### ISSUE TITLE
Typescript definitions do not expose class "Text"

### ISSUE THREAD

**Issue by wallride** [marudor/libxmljs2#29]
In d.ts file class `Node` (guess it should be abstract) has only one child `Element` whereas actually there is also `Text` child class.
We need it to produce multiple text nodes (like this: `<root>foo<b>bar</b>baz</root>`) and add them via `element.addChild(textNode)`. Also it is helpful for conditions like `instanceof`.

Could you, please, add missing definitions or explain why not?

(I do understand this feature is not documented and does not actually correlate with docs. But it's the only way I found to produce mixed nodes list with multiple text and element children)

**Comment by sluukkonen** [comment]
This has been fixed in #31
