### ISSUE TITLE
Where did v0.21.4 go?

### ISSUE THREAD

**Issue by JonnyBlackburnCore** [marudor/libxmljs2#4]
I'm using version 0.21.4 in a project, but noticed this morning that it has been deleted, causing my builds to fail. Just wondering why it has been deleted?
I've updated to 0.26.0 now

**Comment by marudor** [comment]
I "unforked" this repository. (I rewrote a lot and this is not really a fork anymore)
Sadly I forgot that this removes all releases.
I changed the CI before the 0.25.4 release. The CI for all versions before that is no longer working => I can't easily recreate the artifacts.
