### ISSUE TITLE
Cannot import into TypeScript, even using existing types

### ISSUE THREAD

**Issue by antoni-g** [marudor/libxmljs2#84]
Hi all,

I have been typing to use the community provided types for libxmljs with libxmljs2.
However, I'm unable to import the module even with all types included.

- libxmljs2 exists under `node_modules`
- index.d.ts exists under `node_mdules/@types/libxmljs`
- `"moduleResolution": "node",` is set in `tsconfig.json`
- I also tried ```"typeRoots": [ "node_modules/@types" ],``` from `node_modules`
- tried using only `import {parseXml} from 'libxmljs2';`
- as a last resort, I tried copying `node_mdules/@types/libxmljs` into `node_mdules/@types/libxmljs2`

```import * as libxmljs from 'libxmljs2';```

```libxmljs.parseXml(value);```

produces the following issue once any library method (in this case parseXml) is called at compile time:

```×
TypeError: exists is not a function
Function.getRoot
node_modules/bindings/bindings.js:203
  200 |   dir = process.cwd();
  201 | }
  202 | if (
> 203 |   exists(join(dir, 'package.json')) ||
  204 |   exists(join(dir, 'node_modules'))
  205 | ) {
  206 |   // Found the 'package.json' file or 'node_modules' dir; we're done
View compiled
bindings
node_modules/bindings/bindings.js:82
  79 | 
  80 | // Get the module root
  81 | if (!opts.module_root) {
> 82 |   opts.module_root = exports.getRoot(exports.getFileName());
  83 | }
  84 | 
  85 | // Ensure the given bindings name ends with .node
View compiled
./node_modules/libxmljs2/lib/bindings.js
node_modules/libxmljs2/lib/bindings.js:1
> 1 | module.exports = require('bindings')('xmljs');
  2 | 
  3 | 
  4 | 
View compiled
__webpack_require__```

**Comment by sluukkonen** [comment]
libxmljs2 has [built-in typings](https://github.com/marudor/libxmljs2/blob/main/index.d.ts). Why are you trying to use libxmljs typings with it?
