### ISSUE TITLE
Undocumented breaking changes: `TypeError: text.path is not a function`

### ISSUE THREAD

**Issue by Brobin** [marudor/libxmljs2#9]
**Edit**: Well, I think I found the culprit. Breaking changes should be documented somewhere besides in a commit message. Can we get some docs in the repo instead of just the wiki? https://github.com/marudor/libxmljs2/commit/0bd7ab8fe7f936fca5c6878cad1c603b6af3d24f

---------

I'm trying to port our existing codebase from libxmljs to libxmljs2 in order to update Node, and I'm running into this regression. I'm not sure if the API here has changed or if the bindings themselves have changed. Any tips for fixing this?

```js
const libxmljs = require('libxmljs');
const libxmljs2 = require('libxmljs2');

const xml = `<?xml version="1.0" encoding="utf-8"?>
<Name>Test</Name>
`;

describe('libxmljs', () => {
  it('has path for text nodes', () => {
    const doc = libxmljs.parseXmlString(xml);
    const text = doc.get('/Name').childNodes()[0];

    expect(text.type()).to.equal('text');
    expect(text.path()).to.equal('/Name/text()');
  });
});

describe('libxmljs2', () => {
  it('has path for text nodes', () => {
    const doc = libxmljs2.parseXmlString(xml);
    const text = doc.get('/Name').childNodes()[0];

    expect(text.type()).to.equal('text');
    expect(text.path()).to.equal('/Name/text()');
  });
});
```

```
  libxmljs
    ✓ has path for text nodes

  libxmljs2
    1) has path for text nodes


  1 passing (29ms)
  1 failing
```

**Comment by Brobin** [comment]
Well, I think I found the culprit. This should be documented somewhere besides in a commit message. Can we get some docs in the repo instead of just the wiki? https://github.com/marudor/libxmljs2/commit/0bd7ab8fe7f936fca5c6878cad1c603b6af3d24f

**Comment by marudor** [comment]
I'm sorry for that :/
Wasn't my intention to make that breaking change without documentation.
Can you live with that or would you need some new way to get back the old behavior?

**Comment by Brobin** [comment]
Ideally, we'd like to have that functionality back, or at least an easier way to upgrade. End goal is to get on node 14. We can do node 12 in the meantime on v0.25.5, but we'd like to stay up to date as you make releases.

**Comment by Brobin** [comment]
Could we also maybe move the docs off the wiki into the repo so they can be contributed to? I would be willing to help out

**Comment by marudor** [comment]
I would prefer that as well. The current docs are copied from libxmljs I personally never changed them (Cause the main focus at the start was to fix the problems I had with libxmljs)
So If you would like to move them I'm all for that!

**Comment by marudor** [comment]
I just created a fix for your problem (altough a bit dirty)
It will add the path() method to text.

**Comment by marudor** [comment]
0.26.2 should solve your problem.

**Comment by Brobin** [comment]
Could we get the `name` function back too?

**Comment by marudor** [comment]
v0.26.3 should fix your problem.
If not feel free to ping me again
